import random
from datetime import datetime, timedelta

# 1. THE ARTISTS LIST
artists = [
  "dreamo rap",
  "gaze rap",
  "shoegaze ambient",
  "dreampop trap",
  "ethereal rap",
  "angelic trap",
  "dreamy trap",
  "ambient guitar trap",
  "reverb guitar beat",
  "nostalgic trap",
  "sad ambient trap",
  "forest ambient",
  "forest trap",
  "nature ambient",
  "fairy trap",
  "druid ambient",
  "fantasy trap",
  "rpg ambient",
  "tavern ambient",
  "ritual trap",
  "occult ambient",
  "witch house trap",
  "dark ritual ambient",
  "gothic trap",
  "dark ambient trap",
  "tape ambient",
  "cassette trap",
  "vhs aesthetic beat",
  "degraded audio trap",
  "lofi ambient trap",
  "analog texture beat",
  "coldwave trap",
  "minimal wave beat",
  "dark synth trap",
  "post punk trap",
  "space ambient trap",
  "cosmic trap",
  "astral ambient",
  "sci fi trap",
  "night drive trap",
  "lonely trap",
  "heartbreak ambient",
  "emotional trap",
  "post rock trap",
  "cinematic ambient trap",
  "guitar cinematic beat",
  "noise trap",
  "industrial ambient trap",
  "eminem",
  "chill rap",
  "dungeon synth",
  "vegyn",
  "actress",
  "mdot",
  "jersey club",
  "Krushclub",
  "Jerk",
  "baile funk",
  "favela",
  "Sigilkore",
  "glitch",
  "hyperpop",
  "Amapiano",
  "Afro house",
  "Speed garage",
  "glitchcore",
  "digicore",
  "LatinCore",
  "uwuracha",
  "niche",
  "Reggaeton",
  "cumbia",
  "Guaracha",
  "Dembow",
  "HexD",
  "ambient",
  "Post-hyperpop",
  "RKT",
  "sierreño",
  "trap-reggaeton",
  "baddie",
  "micro",
  "nettspend",
  "xaviersobased",
  "luci4",
  "yhapojj",
  "black kray",
  "hi-c",
  "acid souljah",
  "slayworld",
  "1c34",
  "surf gang",
  "evilgiane",
  "phreshboyswag",
  "nosgov",
  "d0llywood1",
  "pitfall",
  "capoxxo",
  "pvscale",
  "midwxst",
  "saturn",
  "angelus",
  "kuru",
  "hardstyle trap",
  "ragecore",
  "plugg",
  "dark plugg",
  "glo beats",
  "cloud drill",
  "sample drill",
  "rage jersey",
  "jerk drill",
  "ambient jersey",
  "opium",
  "vamp rage",
  "cyber rage",
  "glitch jersey",
  "industrial trap",
  "noise rap",
  "distorted trap",
  "lofi plugg",
  "dream plugg",
  "emo plugg",
  "fairy trap",
  "fantasy trap",
  "ethereal rap",
  "sigil ambient",
  "dark ambient trap",
  "glitch phonk",
  "jersey phonk",
  "baile rage",
  "funk mandelão" ]
# 2. THE STYLES LIST (Combined Sub-genres & Vibes)
styles = [
    "mortiis",
     "old tower",
     "fief",
     "erang",
     "fogweaver",
     "secret stairways",
     "gnoll",
     "thangorodrim",
     "elffor",
     "heimat der katastrophe",
     "chaucerian myth",
     "dwalin",
     "vindkaldr",
     "umbral specter",
     "pathworn pilgrim",
     "keys of orthanc",
     "tales under the oak",
     "fen walker",
     "borg",
     "til det bergens skyggene",
     "dark ambient",
     "medieval ambient",
     "fantasy ambient",
     "neo medieval",
     "castle synth",
     "forest synth",
     "winter synth",
     "kobold synth",
     "tavern music",
     "rpg soundtrack",
     "lute ambient",
     "bardcore",
     "darkwave ambient",
     "occult ambient",
     "ritual ambient",
     "druidic ambient",
     "pagan ambient",
     "black ambient",
     "lofi medieval",
     "tape ambient",
     "cassette ambient",
     "minimal synth fantasy",
     "gothic ambient",
     "etherial dungeon",
     "mythic ambient",
     "ancient ambient",
     "ruins ambient",
     "fog ambient",
     "dungeon ambient",
      "nettspend",
      "xaviersobased",
      "luci4",
      "yhapojj",
      "black kray",
      "hi-c",
      "acid souljah",
      "slayworld",
      "1c34",
      "surf gang",
      "evilgiane",
      "phreshboyswag",
      "nosgov",
      "d0llywood1",
      "pitfall",
      "capoxxo",
      "pvscale",
      "midwxst",
      "saturn",
      "angelus",
      "kuru",
      "hardstyle trap",
      "ragecore",
      "plugg",
      "dark plugg",
      "glo beats",
      "cloud drill",
      "sample drill",
      "rage jersey",
      "jerk drill",
      "ambient jersey",
      "opium",
      "vamp rage",
      "cyber rage",
      "glitch jersey",
      "industrial trap",
      "noise rap",
      "distorted trap",
      "lofi plugg",
      "dream plugg",
      "emo plugg",
      "fairy trap",
      "fantasy trap",
      "ethereal rap",
      "sigil ambient",
      "dark ambient trap",
      "glitch phonk",
      "jersey phonk",
      "baile rage",
      "funk mandelão",
      "eminem",
      "chill rap",
      "dungeon synth",
      "vegyn",
      "actress",
      "mdot",
      "jersey club",
      "Krushclub",
      "Jerk",
      "baile funk",
      "favela",
      "Sigilkore",
      "glitch",
      "hyperpop",
      "Amapiano",
      "Afro house",
      "Speed garage",
      "glitchcore",
      "digicore",
      "LatinCore",
      "uwuracha",
      "niche",
      "Reggaeton",
      "cumbia",
      "Guaracha",
      "Dembow",
      "HexD",
      "ambient",
      "Post-hyperpop",
      "RKT",
      "sierreño",
      "trap-reggaeton",
      "baddie",
      "micro"
]

def get_random_date(start_year=2014, end_year=2026):
    """Generates a completely random date within the given year range."""
    start_date = datetime(start_year, 1, 1)
    end_date = datetime(end_year, 12, 31)
    
    # Calculate total days between start and end
    days_between = (end_date - start_date).days
    random_days = random.randrange(days_between)
    
    random_date = start_date + timedelta(days=random_days)
    return random_date.strftime("%Y-%m-%d")

def build_matrix():
    # Using a set ensures we never generate duplicate queries in the same batch
    final_queries = set()
    target_amount = 1000
    
    print(f"🧠 Generating {target_amount} randomized 'Time Machine' queries...")

    while len(final_queries) < target_amount:
        artist = random.choice(artists)
        style = random.choice(styles)
        
        # Build the core query
        query = f'intitle:"type beat" {style} {artist}'
        
        # 33% chance of no date, 33% before date, 33% after date
        date_logic = random.choice(["none", "before", "after"])
        
        if date_logic == "before":
            query += f' before:{get_random_date()}'
        elif date_logic == "after":
            query += f' after:{get_random_date()}'
            
        final_queries.add(query)

    with open("queries.txt", "w") as f:
        for q in final_queries:
            f.write(q + "\n")
    
    print("✅ Success! Check queries.txt for your randomized hit list.")
    print("🚀 You're ready to run python3 scraper.py now.")

if __name__ == "__main__":
    build_matrix()